# ======================== NODE api Configuration ===========================
# ---------------------------------- System -----------------------------------
#
system_name: NodeApi
#
# ----------------------------------- Paths ------------------------------------
#
# Path to log files:
#
path_log: /logs
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http_port: 8082
#
# For more information, consult the network module documentation.
# ---------------------------------- For Third Party Application -----------------------------------
#
mongodb_port: 27017
mongodb_url: mongodb://localhost:27017/
mongodb_database: sayantan
